# Gunakan base image Java 21
FROM openjdk:21

# Set working directory di container
WORKDIR /app

# Copy file JAR dari target build ke container
COPY build/libs/*.jar app.jar

# Expose port yang digunakan aplikasi
EXPOSE 8080

# Konfigurasi environment default
ENV SPRING_PROFILES_ACTIVE=production

# Jalankan aplikasi
ENTRYPOINT ["java", "-jar", "/app/app.jar"]